AfterShip.api_key = '5eacf259-37ab-4f20-a83c-047ee26e872e'

COURIER ={["ITA"]=>
  [{:courier=>"italy-sda", :country=>["ITA"]},
   {:courier=>"sgt-it", :country=>["ITA"]},
   {:courier=>"poste-italiane-paccocelere", :country=>["ITA"]},
   {:courier=>"poste-italiane", :country=>["ITA"]},
   {:courier=>"tnt-click", :country=>["ITA"]},
   {:courier=>"gls-italy", :country=>["ITA"]},
   {:courier=>"fercam", :country=>["ITA"]},
   {:courier=>"tntpost-it", :country=>["ITA"]},
   {:courier=>"brt-it", :country=>["ITA"]},
   {:courier=>"tnt-it", :country=>["ITA"]},
   {:courier=>"dmm-network", :country=>["ITA"]},
   {:courier=>"brt-it-parcelid", :country=>["ITA"]},
   {:courier=>"hermes-it", :country=>["ITA"]},
   {:courier=>"sailpost", :country=>["ITA"]}],
 ["ZAF"]=>
  [{:courier=>"specialisedfreight-za", :country=>["ZAF"]},
   {:courier=>"fastway-za", :country=>["ZAF"]},
   {:courier=>"sapo", :country=>["ZAF"]},
   {:courier=>"dpe-za", :country=>["ZAF"]},
   {:courier=>"dawnwing", :country=>["ZAF"]},
   {:courier=>"courierit", :country=>["ZAF"]},
   {:courier=>"ramgroup-za", :country=>["ZAF"]},
   {:courier=>"thecourierguy", :country=>["ZAF"]},
   {:courier=>"collivery", :country=>["ZAF"]}],
 ["USA"]=>
  [{:courier=>"usps", :country=>["USA"]},
   {:courier=>"ensenda", :country=>["USA"]},
   {:courier=>"yrc", :country=>["USA"]},
   {:courier=>"asendia-usa", :country=>["USA"]},
   {:courier=>"globegistics", :country=>["USA"]},
   {:courier=>"ups-mi", :country=>["USA"]},
   {:courier=>"lasership", :country=>["USA"]},
   {:courier=>"old-dominion", :country=>["USA"]},
   {:courier=>"abf", :country=>["USA"]},
   {:courier=>"i-parcel", :country=>["USA"]},
   {:courier=>"ontrac", :country=>["USA"]},
   {:courier=>"rrdonnelley", :country=>["USA"]},
   {:courier=>"con-way", :country=>["USA"]},
   {:courier=>"echo", :country=>["USA"]},
   {:courier=>"expeditors", :country=>["USA"]},
   {:courier=>"imexglobalsolutions", :country=>["USA"]},
   {:courier=>"yakit", :country=>["USA"]},
   {:courier=>"mailamericas", :country=>["USA"]},
   {:courier=>"amazon-logistics", :country=>["USA"]},
   {:courier=>"gsi-express", :country=>["USA"]},
   {:courier=>"aprisaexpress", :country=>["USA"]},
   {:courier=>"dylt", :country=>["USA"]},
   {:courier=>"amazon-fba-us", :country=>["USA"]},
   {:courier=>"saia-freight", :country=>["USA"]}],
 ["SGP"]=>
  [{:courier=>"zalora-7-eleven", :country=>["SGP"]},
   {:courier=>"singapore-speedpost", :country=>["SGP"]},
   {:courier=>"taqbin-sg", :country=>["SGP"]},
   {:courier=>"singapore-post", :country=>["SGP"]},
   {:courier=>"ninjavan", :country=>["SGP"]},
   {:courier=>"parcelpost-sg", :country=>["SGP"]},
   {:courier=>"detrack", :country=>["SGP"]},
   {:courier=>"parcel-express", :country=>["SGP"]},
   {:courier=>"qxpress", :country=>["SGP"]},
   {:courier=>"nhans-solutions", :country=>["SGP"]},
   {:courier=>"rzyexpress", :country=>["SGP"]},
   {:courier=>"kgmhub", :country=>["SGP"]},
   {:courier=>"raiderex", :country=>["SGP"]},
   {:courier=>"courex", :country=>["SGP"]},
   {:courier=>"roadbull", :country=>["SGP"]},
   {:courier=>"simplypost", :country=>["SGP"]},
   {:courier=>"zyllem", :country=>["SGP"]}],
 ["IND"]=>
  [{:courier=>"india-post-int", :country=>["IND"]},
   {:courier=>"gati-kwe", :country=>["IND"]},
   {:courier=>"safexpress", :country=>["IND"]},
   {:courier=>"red-express-wb", :country=>["IND"]},
   {:courier=>"professional-couriers", :country=>["IND"]},
   {:courier=>"gojavas", :country=>["IND"]},
   {:courier=>"red-express", :country=>["IND"]},
   {:courier=>"dtdc", :country=>["IND"]},
   {:courier=>"india-post", :country=>["IND"]},
   {:courier=>"delhivery", :country=>["IND"]},
   {:courier=>"ecom-express", :country=>["IND"]},
   {:courier=>"bluedart", :country=>["IND"]},
   {:courier=>"xpressbees", :country=>["IND"]},
   {:courier=>"dotzot", :country=>["IND"]},
   {:courier=>"first-flight", :country=>["IND"]},
   {:courier=>"delcart-in", :country=>["IND"]},
   {:courier=>"parcelled-in", :country=>["IND"]},
   {:courier=>"nuvoex", :country=>["IND"]},
   {:courier=>"scudex-express", :country=>["IND"]},
   {:courier=>"ajexpress", :country=>["IND"]},
   {:courier=>"ekart", :country=>["IND"]},
   {:courier=>"holisol", :country=>["IND"]},
   {:courier=>"shreetirupati", :country=>["IND"]}],
 ["BEL"]=>[{:courier=>"bpost", :country=>["BEL"]}, {:courier=>"b2ceurope", :country=>["BEL"]}, {:courier=>"landmark-global", :country=>["BEL"]}],
 ["PRT"]=>[{:courier=>"chronopost-portugal", :country=>["PRT"]}, {:courier=>"portugal-ctt", :country=>["PRT"]}, {:courier=>"adicional", :country=>["PRT"]}],
 ["TUR"]=>[{:courier=>"ptt-posta", :country=>["TUR"]}],
 ["ESP"]=>
  [{:courier=>"spain-correos-es", :country=>["ESP"]},
   {:courier=>"envialia", :country=>["ESP"]},
   {:courier=>"nacex-spain", :country=>["ESP"]},
   {:courier=>"dhl-es", :country=>["ESP"]},
   {:courier=>"correosexpress", :country=>["ESP"]},
   {:courier=>"redur-es", :country=>["ESP"]},
   {:courier=>"asm", :country=>["ESP"]},
   {:courier=>"mrw-spain", :country=>["ESP"]},
   {:courier=>"packlink", :country=>["ESP"]},
   {:courier=>"cbl-logistica", :country=>["ESP"]},
   {:courier=>"abcustom", :country=>["ESP"]}],
 ["SAU"]=>[{:courier=>"saudi-post", :country=>["SAU"]}, {:courier=>"smsa-express", :country=>["SAU"]}],
 ["IRL"]=>
  [{:courier=>"dpd-ireland", :country=>["IRL"]},
   {:courier=>"nightline", :country=>["IRL"]},
   {:courier=>"an-post", :country=>["IRL"]},
   {:courier=>"fastway-ireland", :country=>["IRL"]},
   {:courier=>"wiseloads", :country=>["IRL"]},
   {:courier=>"skynetworldwide-uae", :country=>["IRL"]}],
 ["AUT"]=>[{:courier=>"austrian-post-registered", :country=>["AUT"]}, {:courier=>"austrian-post", :country=>["AUT"]}],
 ["THA"]=>
  [{:courier=>"kerry-logistics", :country=>["THA"]},
   {:courier=>"thailand-post", :country=>["THA"]},
   {:courier=>"dynamic-logistics", :country=>["THA"]},
   {:courier=>"fastrak-th", :country=>["THA"]},
   {:courier=>"alphafast", :country=>["THA"]},
   {:courier=>"sendit", :country=>["THA"]},
   {:courier=>"cj-korea-thai", :country=>["THA"]},
   {:courier=>"acommerce", :country=>["THA"]},
   {:courier=>"ninjavan-thai", :country=>["THA"]},
   {:courier=>"nim-express", :country=>["THA"]},
   {:courier=>"skybox", :country=>["THA"]}],
 ["NOR"]=>[{:courier=>"posten-norge", :country=>["NOR"]}],
 ["HKG"]=>
  [{:courier=>"hong-kong-post", :country=>["HKG"]},
   {:courier=>"taqbin-hk", :country=>["HKG"]},
   {:courier=>"rpxonline", :country=>["HKG"]},
   {:courier=>"tgx", :country=>["HKG"]},
   {:courier=>"costmeticsnow", :country=>["HKG"]},
   {:courier=>"sekologistics", :country=>["HKG"]},
   {:courier=>"omniparcel", :country=>["HKG"]},
   {:courier=>"dhl-hk", :country=>["HKG"]},
   {:courier=>"smooth", :country=>["HKG"]},
   {:courier=>"pickup", :country=>["HKG"]},
   {:courier=>"janco", :country=>["HKG"]},
   {:courier=>"palexpress", :country=>["HKG"]}],
 ["ESP", "PRT"]=>
  [{:courier=>"portugal-seur", :country=>["ESP", "PRT"]}, {:courier=>"international-seur", :country=>["ESP", "PRT"]}, {:courier=>"spanish-seur", :country=>["ESP", "PRT"]}],
 ["CAN"]=>
  [{:courier=>"canada-post", :country=>["CAN"]},
   {:courier=>"greyhound", :country=>["CAN"]},
   {:courier=>"canpar", :country=>["CAN"]},
   {:courier=>"purolator", :country=>["CAN"]},
   {:courier=>"chit-chat", :country=>["CAN"]}],
 []=>
  [{:courier=>"aramex", :country=>[]},
   {:courier=>"dachser", :country=>[]},
   {:courier=>"kn", :country=>[]},
   {:courier=>"dhl-global-mail", :country=>[]},
   {:courier=>"ups-freight", :country=>[]},
   {:courier=>"fedex", :country=>[]},
   {:courier=>"dhl", :country=>[]},
   {:courier=>"ups", :country=>[]},
   {:courier=>"skynetworldwide", :country=>[]},
   {:courier=>"tnt", :country=>[]},
   {:courier=>"gls", :country=>[]},
   {:courier=>"bpost-international", :country=>[]},
   {:courier=>"trakpak", :country=>[]},
   {:courier=>"dhl-pieceid", :country=>[]},
   {:courier=>"dpd", :country=>[]},
   {:courier=>"dsv", :country=>[]},
   {:courier=>"newgistics", :country=>[]},
   {:courier=>"fedex-freight", :country=>[]},
   {:courier=>"tnt-reference", :country=>[]},
   {:courier=>"tnt-uk-reference", :country=>[]},
   {:courier=>"dhl-global-forwarding", :country=>[]},
   {:courier=>"dhl-active-tracing", :country=>[]},
   {:courier=>"copa-courier", :country=>[]},
   {:courier=>"mikropakket", :country=>[]},
   {:courier=>"kiala", :country=>[]},
   {:courier=>"logwin-logistics", :country=>[]},
   {:courier=>"eurodis", :country=>[]},
   {:courier=>"tipsa", :country=>[]},
   {:courier=>"efs", :country=>[]},
   {:courier=>"ddexpress", :country=>[]},
   {:courier=>"ezship", :country=>[]},
   {:courier=>"demandship", :country=>[]},
   {:courier=>"mudita", :country=>[]},
   {:courier=>"uds", :country=>[]},
   {:courier=>"star-track-courier", :country=>[]},
   {:courier=>"sky-postal", :country=>[]}],
 ["HKG", "SGP"]=>[{:courier=>"dhl-global-mail-asia", :country=>["HKG", "SGP"]}, {:courier=>"quantium", :country=>["HKG", "SGP"]}],
 ["POL"]=>
  [{:courier=>"dhl-poland", :country=>["POL"]},
   {:courier=>"siodemka", :country=>["POL"]},
   {:courier=>"opek", :country=>["POL"]},
   {:courier=>"poczta-polska", :country=>["POL"]},
   {:courier=>"dpd-poland", :country=>["POL"]},
   {:courier=>"inpost-paczkomaty", :country=>["POL"]}],
 ["HUN"]=>[{:courier=>"magyar-posta", :country=>["HUN"]}],
 ["UKR"]=>[{:courier=>"nova-poshta", :country=>["UKR"]}, {:courier=>"ukrposhta", :country=>["UKR"]}, {:courier=>"nova-poshtaint", :country=>["UKR"]}],
 ["KHM"]=>[{:courier=>"cambodia-post", :country=>["KHM"]}],
 ["PHL"]=>
  [{:courier=>"xend", :country=>["PHL"]},
   {:courier=>"2go", :country=>["PHL"]},
   {:courier=>"jam-express", :country=>["PHL"]},
   {:courier=>"air21", :country=>["PHL"]},
   {:courier=>"lbcexpress", :country=>["PHL"]},
   {:courier=>"raf", :country=>["PHL"]},
   {:courier=>"airspeed", :country=>["PHL"]},
   {:courier=>"ninjavan-philippines", :country=>["PHL"]}],
 ["FRA"]=>
  [{:courier=>"chronopost-france", :country=>["FRA"]},
   {:courier=>"geodis-calberson-fr", :country=>["FRA"]},
   {:courier=>"tnt-fr", :country=>["FRA"]},
   {:courier=>"la-poste-colissimo", :country=>["FRA"]},
   {:courier=>"bert-fr", :country=>["FRA"]},
   {:courier=>"colissimo", :country=>["FRA"]},
   {:courier=>"colis-prive", :country=>["FRA"]},
   {:courier=>"exapaq", :country=>["FRA"]},
   {:courier=>"sic-teliway", :country=>["FRA"]},
   {:courier=>"geodis-espace", :country=>["FRA"]}],
 ["AUS"]=>
  [{:courier=>"tnt-au", :country=>["AUS"]},
   {:courier=>"star-track", :country=>["AUS"]},
   {:courier=>"fastway-au", :country=>["AUS"]},
   {:courier=>"toll-ipec", :country=>["AUS"]},
   {:courier=>"australia-post", :country=>["AUS"]},
   {:courier=>"toll-priority", :country=>["AUS"]},
   {:courier=>"star-track-express", :country=>["AUS"]},
   {:courier=>"ubi-logistics", :country=>["AUS"]},
   {:courier=>"bondscouriers", :country=>["AUS"]},
   {:courier=>"couriers-please", :country=>["AUS"]},
   {:courier=>"adsone", :country=>["AUS"]},
   {:courier=>"directfreight-au", :country=>["AUS"]},
   {:courier=>"dtdc-au", :country=>["AUS"]},
   {:courier=>"australia-post-sftp", :country=>["AUS"]},
   {:courier=>"sendle", :country=>["AUS"]},
   {:courier=>"hunter-express", :country=>["AUS"]},
   {:courier=>"xl-express", :country=>["AUS"]},
   {:courier=>"alliedexpress", :country=>["AUS"]},
   {:courier=>"capital", :country=>["AUS"]}],
 ["GRC"]=>
  [{:courier=>"acscourier", :country=>["GRC"]},
   {:courier=>"elta-courier", :country=>["GRC"]},
   {:courier=>"taxydromiki", :country=>["GRC"]},
   {:courier=>"speedcouriers-gr", :country=>["GRC"]},
   {:courier=>"easy-mail", :country=>["GRC"]}],
 ["GBR"]=>
  [{:courier=>"uk-mail", :country=>["GBR"]},
   {:courier=>"deltec-courier", :country=>["GBR"]},
   {:courier=>"interlink-express", :country=>["GBR"]},
   {:courier=>"dpd-uk", :country=>["GBR"]},
   {:courier=>"dx", :country=>["GBR"]},
   {:courier=>"xdp-uk", :country=>["GBR"]},
   {:courier=>"hermes", :country=>["GBR"]},
   {:courier=>"apc-overnight", :country=>["GBR"]},
   {:courier=>"homedirect-logistics", :country=>["GBR"]},
   {:courier=>"tuffnells", :country=>["GBR"]},
   {:courier=>"norsk-global", :country=>["GBR"]},
   {:courier=>"royal-mail", :country=>["GBR"]},
   {:courier=>"parcel-force", :country=>["GBR"]},
   {:courier=>"skynetworldwide-uk", :country=>["GBR"]},
   {:courier=>"yodel", :country=>["GBR"]},
   {:courier=>"yodel-international", :country=>["GBR"]},
   {:courier=>"panther", :country=>["GBR"]},
   {:courier=>"collectplus", :country=>["GBR"]},
   {:courier=>"tnt-uk", :country=>["GBR"]},
   {:courier=>"arrowxl", :country=>["GBR"]},
   {:courier=>"fedex-uk", :country=>["GBR"]},
   {:courier=>"myhermes-uk", :country=>["GBR"]},
   {:courier=>"asendia-uk", :country=>["GBR"]},
   {:courier=>"xdp-uk-reference", :country=>["GBR"]},
   {:courier=>"apc-overnight-reference", :country=>["GBR"]},
   {:courier=>"interlink-express-reference", :country=>["GBR"]},
   {:courier=>"jersey-post", :country=>["GBR"]},
   {:courier=>"dx-freight", :country=>["GBR"]},
   {:courier=>"wndirect", :country=>["GBR"]},
   {:courier=>"rpd2man", :country=>["GBR"]},
   {:courier=>"panther-reference", :country=>["GBR"]},
   {:courier=>"whistl", :country=>["GBR"]},
   {:courier=>"birdsystem", :country=>["GBR"]},
   {:courier=>"panther-order-number", :country=>["GBR"]}],
 ["MYS"]=>
  [{:courier=>"skynet", :country=>["MYS"]},
   {:courier=>"gdex", :country=>["MYS"]},
   {:courier=>"taqbin-my", :country=>["MYS"]},
   {:courier=>"citylinkexpress", :country=>["MYS"]},
   {:courier=>"malaysia-post-posdaftar", :country=>["MYS"]},
   {:courier=>"malaysia-post", :country=>["MYS"]},
   {:courier=>"airpak-express", :country=>["MYS"]},
   {:courier=>"mypostonline", :country=>["MYS"]},
   {:courier=>"abxexpress-my", :country=>["MYS"]},
   {:courier=>"kangaroo-my", :country=>["MYS"]},
   {:courier=>"nationwide-my", :country=>["MYS"]},
   {:courier=>"ninjavan-my", :country=>["MYS"]},
   {:courier=>"matdespatch", :country=>["MYS"]},
   {:courier=>"jocom", :country=>["MYS"]},
   {:courier=>"line", :country=>["MYS"]},
   {:courier=>"instant", :country=>["MYS"]},
   {:courier=>"collectco", :country=>["MYS"]},
   {:courier=>"zepto-express", :country=>["MYS"]},
   {:courier=>"jinsung", :country=>["MYS"]},
   {:courier=>"wepost", :country=>["MYS"]}],
 ["NGA"]=>[{:courier=>"nipost", :country=>["NGA"]}, {:courier=>"courier-plus", :country=>["NGA"]}],
 ["ARG"]=>[{:courier=>"oca-ar", :country=>["ARG"]}, {:courier=>"correo-argentino", :country=>["ARG"]}],
 ["MEX"]=>
  [{:courier=>"aeroflash", :country=>["MEX"]},
   {:courier=>"mexico-senda-express", :country=>["MEX"]},
   {:courier=>"mexico-redpack", :country=>["MEX"]},
   {:courier=>"estafeta", :country=>["MEX"]},
   {:courier=>"correos-de-mexico", :country=>["MEX"]},
   {:courier=>"paquetexpress", :country=>["MEX"]}],
 ["JPN"]=>[{:courier=>"japan-post", :country=>["JPN"]}, {:courier=>"sagawa", :country=>["JPN"]}, {:courier=>"taqbin-jp", :country=>["JPN"]}],
 ["VNM"]=>
  [{:courier=>"vnpost", :country=>["VNM"]},
   {:courier=>"viettelpost", :country=>["VNM"]},
   {:courier=>"ghn", :country=>["VNM"]},
   {:courier=>"vnpost-ems", :country=>["VNM"]},
   {:courier=>"kerryttc-vn", :country=>["VNM"]}],
 ["NLD"]=>
  [{:courier=>"postnl-3s", :country=>["NLD"]},
   {:courier=>"gls-netherlands", :country=>["NLD"]},
   {:courier=>"transmission-nl", :country=>["NLD"]},
   {:courier=>"postnl-international", :country=>["NLD"]},
   {:courier=>"dhl-nl", :country=>["NLD"]},
   {:courier=>"dhlparcel-nl", :country=>["NLD"]},
   {:courier=>"postnl", :country=>["NLD"]},
   {:courier=>"dynalogic", :country=>["NLD"]}],
 ["IDN"]=>
  [{:courier=>"tiki", :country=>["IDN"]},
   {:courier=>"first-logistics", :country=>["IDN"]},
   {:courier=>"wahana", :country=>["IDN"]},
   {:courier=>"pos-indonesia", :country=>["IDN"]},
   {:courier=>"pos-indonesia-int", :country=>["IDN"]},
   {:courier=>"jne", :country=>["IDN"]},
   {:courier=>"pandulogistics", :country=>["IDN"]},
   {:courier=>"lion-parcel", :country=>["IDN"]},
   {:courier=>"rpx", :country=>["IDN"]},
   {:courier=>"ninjavan-id", :country=>["IDN"]},
   {:courier=>"rcl", :country=>["IDN"]}],
 ["CZE"]=>[{:courier=>"ceska-posta", :country=>["CZE"]}],
 ["CHN"]=>
  [{:courier=>"china-ems", :country=>["CHN"]},
   {:courier=>"ppbyb", :country=>["CHN"]},
   {:courier=>"ec-firstclass", :country=>["CHN"]},
   {:courier=>"aupost-china", :country=>["CHN"]},
   {:courier=>"wedo", :country=>["CHN"]},
   {:courier=>"yundaex", :country=>["CHN"]},
   {:courier=>"equick-cn", :country=>["CHN"]},
   {:courier=>"4px", :country=>["CHN"]},
   {:courier=>"jcex", :country=>["CHN"]},
   {:courier=>"post56", :country=>["CHN"]},
   {:courier=>"sto", :country=>["CHN"]},
   {:courier=>"gofly", :country=>["CHN"]},
   {:courier=>"empsexpress", :country=>["CHN"]},
   {:courier=>"17postservice", :country=>["CHN"]},
   {:courier=>"szdpex", :country=>["CHN"]},
   {:courier=>"800bestex", :country=>["CHN"]},
   {:courier=>"boxc", :country=>["CHN"]},
   {:courier=>"wishpost", :country=>["CHN"]},
   {:courier=>"sfb2c", :country=>["CHN"]},
   {:courier=>"flytexpress", :country=>["CHN"]},
   {:courier=>"yanwen", :country=>["CHN"]},
   {:courier=>"cnexps", :country=>["CHN"]},
   {:courier=>"zjs-express", :country=>["CHN"]},
   {:courier=>"nanjingwoyuan", :country=>["CHN"]},
   {:courier=>"yunexpress", :country=>["CHN"]},
   {:courier=>"cuckooexpress", :country=>["CHN"]},
   {:courier=>"oneworldexpress", :country=>["CHN"]},
   {:courier=>"hh-exp", :country=>["CHN"]},
   {:courier=>"china-post", :country=>["CHN"]},
   {:courier=>"360lion", :country=>["CHN"]},
   {:courier=>"pfcexpress", :country=>["CHN"]},
   {:courier=>"cpacket", :country=>["CHN"]},
   {:courier=>"yto", :country=>["CHN"]},
   {:courier=>"sfcservice", :country=>["CHN"]},
   {:courier=>"skypostal", :country=>["CHN"]},
   {:courier=>"xq-express", :country=>["CHN"]},
   {:courier=>"dpe-express", :country=>["CHN"]},
   {:courier=>"idexpress", :country=>["CHN"]},
   {:courier=>"buylogic", :country=>["CHN"]},
   {:courier=>"dex-i", :country=>["CHN"]},
   {:courier=>"ruston", :country=>["CHN"]},
   {:courier=>"wanbexpress", :country=>["CHN"]},
   {:courier=>"wise-express", :country=>["CHN"]},
   {:courier=>"zto-express", :country=>["CHN"]},
   {:courier=>"alljoy", :country=>["CHN"]},
   {:courier=>"mxe", :country=>["CHN"]}],
 ["USA", "CAN"]=>[{:courier=>"apc", :country=>["USA", "CAN"]}, {:courier=>"rl-carriers", :country=>["USA", "CAN"]}],
 ["KOR"]=>
  [{:courier=>"cj-gls", :country=>["KOR"]},
   {:courier=>"ecargo-asia", :country=>["KOR"]},
   {:courier=>"korea-post", :country=>["KOR"]},
   {:courier=>"srekorea", :country=>["KOR"]},
   {:courier=>"rocketparcel", :country=>["KOR"]},
   {:courier=>"eparcel-kr", :country=>["KOR"]},
   {:courier=>"rincos", :country=>["KOR"]},
   {:courier=>"doora", :country=>["KOR"]},
   {:courier=>"kpost", :country=>["KOR"]}],
 ["TWN"]=>[{:courier=>"taiwan-post", :country=>["TWN"]}],
 ["BGR"]=>[{:courier=>"bgpost", :country=>["BGR"]}],
 ["BRA"]=>[{:courier=>"brazil-correios", :country=>["BRA"]}, {:courier=>"directlog", :country=>["BRA"]}],
 ["CAN", "USA"]=>[{:courier=>"estes", :country=>["CAN", "USA"]}],
 ["DNK", "SWE"]=>[{:courier=>"postnord", :country=>["DNK", "SWE"]}, {:courier=>"sweden-posten", :country=>["DNK", "SWE"]}],
 ["BLR"]=>[{:courier=>"belpost", :country=>["BLR"]}],
 ["CYP"]=>[{:courier=>"cyprus-post", :country=>["CYP"]}],
 ["HKG", "CHN"]=>[{:courier=>"sf-express", :country=>["HKG", "CHN"]}],
 ["LTU"]=>[{:courier=>"lietuvos-pastas", :country=>["LTU"]}],
 ["CHE"]=>[{:courier=>"swiss-post", :country=>["CHE"]}, {:courier=>"asendia-hk", :country=>["CHE"]}],
 ["DNK"]=>[{:courier=>"danmark-post", :country=>["DNK"]}],
 ["HRV"]=>[{:courier=>"hrvatska-posta", :country=>["HRV"]}],
 ["ROU"]=>[{:courier=>"posta-romana", :country=>["ROU"]}, {:courier=>"dpd-ro", :country=>["ROU"]}],
 ["NZL"]=>
  [{:courier=>"courierpost", :country=>["NZL"]},
   {:courier=>"new-zealand-post", :country=>["NZL"]},
   {:courier=>"fastway-nz", :country=>["NZL"]},
   {:courier=>"mainfreight", :country=>["NZL"]}],
 ["DEU"]=>
  [{:courier=>"hermes-de", :country=>["DEU"]},
   {:courier=>"asendia-de", :country=>["DEU"]},
   {:courier=>"dhl-germany", :country=>["DEU"]},
   {:courier=>"deutsch-post", :country=>["DEU"]},
   {:courier=>"dpd-de", :country=>["DEU"]},
   {:courier=>"raben-group", :country=>["DEU"]}],
 ["SGP", "IND"]=>[{:courier=>"jayonexpress", :country=>["SGP", "IND"]}],
 ["GBR", "FRA", "ESP", "BEL", "CHE", "ITA"]=>[{:courier=>"imxmail", :country=>["GBR", "FRA", "ESP", "BEL", "CHE", "ITA"]}],
 ["FRA", "BEL"]=>[{:courier=>"mondialrelay", :country=>["FRA", "BEL"]}],
 ["ISR"]=>[{:courier=>"israel-post-domestic", :country=>["ISR"]}, {:courier=>"israel-post", :country=>["ISR"]}],
 ["SWE"]=>[{:courier=>"directlink", :country=>["SWE"]}, {:courier=>"dbschenker-se", :country=>["SWE"]}],
 ["ARE"]=>[{:courier=>"emirates-post", :country=>["ARE"]}, {:courier=>"axl", :country=>["ARE"]}, {:courier=>"mara-xpress", :country=>["ARE"]}],
 ["DEU", "AUT"]=>[{:courier=>"dhl-deliverit", :country=>["DEU", "AUT"]}],
 ["BEL", "LUX", "NLD"]=>[{:courier=>"dhl-benelux", :country=>["BEL", "LUX", "NLD"]}],
 ["KWT"]=>[{:courier=>"speedexcourier", :country=>["KWT"]}],
 ["RUS"]=>[{:courier=>"russian-post", :country=>["RUS"]}],
 ["FIN"]=>[{:courier=>"posti", :country=>["FIN"]}, {:courier=>"matkahuolto", :country=>["FIN"]}],
 ["CHL"]=>[{:courier=>"correos-chile", :country=>["CHL"]}],
 ["HKG", "MYS", "CHN", "SGP", "KOR"]=>[{:courier=>"lwe-hk", :country=>["HKG", "MYS", "CHN", "SGP", "KOR"]}],
 ["SGP", "PHL", "MYS"]=>[{:courier=>"jet-ship", :country=>["SGP", "PHL", "MYS"]}],
 ["BIH"]=>[{:courier=>"bh-posta", :country=>["BIH"]}],
 ["SRB"]=>[{:courier=>"post-serbia", :country=>["SRB"]}],
 ["COL"]=>[{:courier=>"4-72", :country=>["COL"]}],
 ["SGP", "HKG"]=>[{:courier=>"dpex", :country=>["SGP", "HKG"]}],
 ["ISL"]=>[{:courier=>"postur-is", :country=>["ISL"]}],
 ["LAO"]=>[{:courier=>"lao-post", :country=>["LAO"]}],
 ["CRI"]=>[{:courier=>"correos-de-costa-rica", :country=>["CRI"]}],
 ["PAK"]=>[{:courier=>"tcs", :country=>["PAK"]}],
 ["EST"]=>[{:courier=>"omniva", :country=>["EST"]}],
 ["CHN", "HKG", "TWN"]=>[{:courier=>"acsworldwide", :country=>["CHN", "HKG", "TWN"]}]}

