TRACKING_URL = "http://www.17track.net/en/track?nums="
TRACKING_COMPANY = "China Division"
UNDEFINED = "undefined"
TIME_FORMAT = "%Y-%m-%d 00:00:00"
TIME_FORMAT_END = "%Y-%m-%d 23:59:59"
STRIPE_PLAINNING = "miskare_pro_plan"
HAVE_TO_CONFIRM = "You have to confirm your email address before continuing."