STRIPE_PUBLISHABLE_KEY: pk_test_XqlMO2iFmCyghF1uad3vSAyP
STRIPE_SECRET_KEY: "sk_test_d8NIKX61NmkbEn7W7JMUGiPs"

USER_MAIL_SERVER: "orgtree.dev@gmail.com"
PASSWORD_MAIL_SERVER: "tranphuhuy"
DEFAULT_FORM_MAILER: "orgtree.dev@gmail.com"
DEFAULT_URL_OPTION: "http://localhost:3000"