STRIPE_PUBLISHABLE_KEY: pk_live_PwSCUwOdNa8lx8CVswv9LFOa
STRIPE_SECRET_KEY: "sk_live_ZW1H6sK7ciWwYmG067mwBTE9"

USER_MAIL_SERVER: "orgtree.dev@gmail.com"
PASSWORD_MAIL_SERVER: "tranphuhuy"
DEFAULT_FORM_MAILER: "orgtree.dev@gmail.com"
DEFAULT_URL_OPTION: "http://miskre.com"