:logfile: log/sidekiq.log
:schedule:
  fetch_tracking_info:
    every: 3h
    class: FetchTrackingInfo
    description: 'Fetching tracking information'
  sync_order:
    every: 1h
    class: SyncOrder
    description: 'Sync orders from shopify'
  sync_customer:
    every: 1h
    class: SyncCustomers
    description: 'Sync customers from shopify'